type StringsType = { [key: string]: any };

const enBase = {
  brand: 'West Riyadh Careers Forum',
  brandShort: 'West Riyadh',
  domain: 'westriyadh.net',
  tagline: 'Your job, next door',
  nav: { home: 'Home', jobs: 'Jobs', cv: 'AI CV Builder', employers: 'Employers', admin: 'Admin', login: 'Sign in', logout: 'Sign out', dashboard: 'My dashboard', wallet: 'Wallet', guide: 'User Guide' },
  hero: {
    eyebrow: 'The first geo-focused hiring platform in West Riyadh',
    titleA: 'Your job,', titleB: 'next door',
    sub: 'A dedicated platform connecting job seekers with employers inside West Riyadh — with real commute distance and time on every job before you apply.',
    searchJob: 'Job title or skill', searchHood: 'Your neighborhood', searchBtn: 'Find nearby jobs',
    calcTitle: 'Calculate your commute before signing up', calcSub: 'Instant value before an account — that is our promise.',
    from: 'From neighborhood', to: 'To job neighborhood', calcBtn: 'Calculate distance & time',
    km: 'km', min: 'min', dailySaved: 'saved daily (round trip) vs. average Riyadh commute',
    ctaJobs: 'Browse jobs', ctaCv: 'Build your CV with AI',
    liveBadge: 'Live — West Riyadh',
  },
  stats: { jobs: 'Active jobs', seekers: 'Registered seekers', hires: 'Successful hires', saved: 'Minutes saved daily', source: 'Indicators from platform database analytics', editable: 'Adjustable from the admin panel' },
  how: {
    title: 'How it works', sub: 'Three steps between you and a job closer to home',
    s1t: 'Set your neighborhood', s1d: 'Enter your basics and home neighborhood — we compute commute time for every job automatically.',
    s2t: 'Discover & compare', s2d: 'Jobs sorted by proximity with professional match score and salary — a clear decision before applying.',
    s3t: 'Apply & track transparently', s3d: 'Track your application step by step; if rejected, the reason is mandatory.',
  },
  ai: {
    title: 'An AI layer serving both sides', sub: 'AI proposes; humans review and approve — never a standalone automated decision.',
    seekerTitle: 'For job seekers',
    f1: 'Build your CV and export an ATS-friendly PDF',
    f2: 'Review and improve wording, rephrasing weak statements',
    f3: 'Tailor your CV to the target job description',
    f4: 'Skill-gap analysis with course and growth suggestions',
    f5: 'Likely interview questions generated from the job post',
    empTitle: 'For employers',
    g1: 'Draft job ads written by AI in your brand identity',
    g2: 'Completeness check before publishing — no incomplete ads',
    g3: 'Candidates ranked with explained match score and skill gaps',
    g4: 'Interview questions & scorecards for your team only',
    g5: 'Reports: time-to-hire, readiness, proximity impact on retention',
  },
  employersCta: {
    title: 'For employers in West Riyadh', sub: 'Qualified candidates who can actually reach your branch on time — transparent points and e-payment.',
    b1: 'Post jobs and manage branches & locations', b2: 'Candidates ranked by fit and arrival time', b3: 'AI-designed job ads in your brand identity', b4: 'Exportable hiring & retention reports',
    cta: 'Start as an employer',
  },
  app: {
    title: 'Mobile app', sub: 'The same experience in your pocket — a Flutter app for iOS & Android with instant status notifications and commute time from your live location.',
    f1: 'Instant push on every status change', f2: 'Jobs near your live GPS location', f3: 'Your CV and interviews, anywhere',
    soon: 'Soon on',
  },
  adsBar: 'Ad space — advertise with us',
  footer: {
    about: 'The digital operating layer of the West Riyadh Careers Forum — a defined geography, a dense local network, results that are hard to copy.',
    platform: 'Platform', support: 'Support', legal: 'Policies',
    terms: 'Terms of Use', privacy: 'Privacy Policy', payment: 'Payment & Refund Policy', points: 'Points Policy', ai: 'AI & Data Controls',
    contact: 'Contact us', rights: 'All rights reserved', coverage: 'Coverage: West Riyadh neighborhoods',
  },
  jobs: {
    title: 'West Riyadh Jobs', sub: 'Every listing shows commute distance and time from your neighborhood',
    sortNearest: 'Nearest to you', sortNewest: 'Newest', sortSalary: 'Highest salary', sortMatch: 'Best match',
    allTypes: 'All types', full: 'Full-time', part: 'Part-time', shift: 'Shifts',
    pickHood: 'Set your home neighborhood to see distance & time', results: 'jobs', promoted: 'Sponsored',
    match: 'match', apply: 'Apply now', applied: 'Applied', details: 'Details',
    salary: 'Salary', sar: 'SAR', hours: 'Hours', applicants: 'applicants', ago: '', day: 'day ago', days: 'days ago', today: 'today', yesterday: 'yesterday',
  },
  job: {
    back: 'Back to jobs', about: 'About the role', reqs: 'Requirements', commute: 'Your commute to work',
    fromHome: 'From your neighborhood', matchTitle: 'Match analysis', matched: 'Matched skills', missing: 'Missing skills — they won\'t block you; we\'ll suggest courses to close them',
    applyNow: 'Apply for this job', appliedDone: 'Application sent — track it in your dashboard',
    interviewPrep: 'Likely interview questions (AI)', prepNote: 'Generated from the actual job description — prepare your answers',
    similar: 'Similar jobs near you', company: 'About the company', verified: 'Verified',
  },
  auth: {
    welcome: 'Welcome to West Riyadh Careers', sub: 'Sign up with simple basics or via your accounts — no friction.',
    login: 'Sign in', register: 'Create account', asSeeker: 'Job seeker', asEmployer: 'Employer',
    name: 'Full name', email: 'Email', phone: 'Mobile number', password: 'Password', company: 'Company name', cr: 'Commercial registration',
    or: 'or via', google: 'Google', twitter: 'X (Twitter)', linkedin: 'LinkedIn', facebook: 'Facebook',
    agreePre: 'I agree to the', agreeMid: 'and', terms: 'Terms of Use', privacy: 'Privacy Policy', payment: 'and the Payment Policy',
    agreeNote: 'By creating an account or signing in via any method, you accept the policies even without opening their links.',
    socialNote: 'OAuth keys (Client ID / Secret) are entered in Admin → Social Login.',
    haveAccount: 'Have an account?', noAccount: 'New here?', continue: 'Continue',
    kimi: 'Sign in with Kimi', realNote: 'A real account on the platform database — your data is saved and synced across devices.',
  },
  onboard: {
    title: 'Complete your profile — one minute', sub: 'Your data is used only for commute time and match scoring.',
    hood: 'Current neighborhood', currentJob: 'Current job (if any)', interests: 'Fields you care about', exp: 'Years of experience', edu: 'Education',
    save: 'Save & continue', skip: 'Later', done: 'Profile complete — jobs are now sorted by proximity',
    detect: 'Detect my location', detecting: 'Detecting your location…', detected: 'Location detected — nearest neighborhood:', locDenied: 'Location unavailable — pick your neighborhood manually; you can edit it later',
    locNote: 'The platform is location-driven: enable location so we capture your coordinates and compute commute time precisely — used for matching only.', zoneWest: 'West Riyadh', zoneSouth: 'South Riyadh',
  }
};

export default enBase;
