// English strings — part 2 (merged in en.ts)
export const enPart2 = {
  cv: {
    title: 'AI CV Builder', sub: 'Enter your data or link your accounts — AI builds the perfect CV, Arabic or English, in one click.',
    stepData: 'Your data', stepLinks: 'Links & files', stepAi: 'AI generation', stepPreview: 'Preview & download',
    fullName: 'Full name', jobTitle: 'Professional title', summary: 'Professional summary', experience: 'Experience', education: 'Education', skills: 'Skills (comma separated)', phone: 'Mobile', email: 'Email',
    linksTitle: 'Link your digital presence', linksSub: 'Paste your links — AI extracts your skills and achievements',
    linkedin: 'LinkedIn URL', twitter: 'X (Twitter) URL', otherLink: 'Other link (portfolio, GitHub…)', upload: 'Upload existing CV or certificates (PDF / images)',
    aiTitle: 'AI engine', aiSub: 'Pick what you need — generation runs through the AI provider connected in the admin panel',
    genSummary: 'Improve & rephrase summary', genAts: 'ATS alignment', genTailor: 'Tailor to a job', genGap: 'Skill-gap analysis',
    tailorPick: 'Pick the target job', generate: 'Generate with AI', generating: 'AI is working…',
    langAr: 'Arabic CV', langEn: 'English CV',
    preview: 'Preview', downloadPdf: 'Download PDF', downloadJpg: 'Download JPG',
    brandingNote: 'CVs carry the platform logo for free. Removing it is a paid service — priced in the admin panel and linked to e-payment.',
    removeLogo: 'Remove logo', logoRemoved: 'Logo-free — paid service activated', payNow: 'Pay & remove logo',
    apiMissing: 'No AI provider connected yet — configure in Admin (provider, API key, model). Preview mode shows a sample result.',
    gapTitle: 'Skill gaps', gapNote: 'Gaps never block you from applying — suggested courses to close them',
    atsOk: 'ATS-friendly', aiResult: 'AI result', editHint: 'You can edit any text before downloading',
  },
  dash: {
    title: 'Seeker dashboard', apps: 'My applications', notifications: 'Notifications', profile: 'My profile',
    stSent: 'Sent', stSeen: 'Viewed', stShort: 'Shortlisted', stInterview: 'Interview', stRejected: 'Not accepted', stHired: 'Hired',
    reason: 'Rejection reason (mandatory)', object: 'Object / request human review', objectSent: 'Your objection was sent for human review — decisions are never left to AI alone.',
    timeline: 'Application journey', empty: 'No applications yet', browse: 'Browse nearby jobs',
    viewJob: 'View job',
  },
  emp: {
    title: 'Employer dashboard', myJobs: 'My jobs', candidates: 'Candidates', newJob: 'New job ad', aiAd: 'AI ad designer', promote: 'Promote', reports: 'Reports',
    points: 'Your points', charge: 'Top up points', balance: 'Current balance',
    candidatesFor: 'Candidates for', commuteTime: 'Arrival time', matchWhy: 'Why matched?', risks: 'Risks',
    aiTitle: 'AI job-ad designer in your brand identity', aiDesc: 'Enter the basics — AI writes a complete ad styled with your brand. Cost is deducted from your points balance.',
    brandColor: 'Brand color', jobTitleIn: 'Job title', branch: 'Branch / neighborhood', need: 'Needs & skills',
    genAd: 'Generate ad', cost: 'Cost', pts: 'pts', insufficient: 'Insufficient balance — top up first',
    adPreview: 'Ad preview', publish: 'Approve & publish',
    completeness: 'Job data completeness', missingFields: 'Missing fields blocking publication',
    promoteTitle: 'Promote job', promoteDesc: 'Sponsored top-of-list placement — priced in the admin panel', days3: '3 days', week: '1 week',
    status: 'Status', active: 'Active', closed: 'Closed', applicantsCol: 'Applicants', actions: 'Actions',
    rep1: 'Time to hire', rep2: 'Candidate readiness', rep3: 'Proximity impact on retention', export: 'Export report',
    rejectionPick: 'Pick a ready reason — mandatory on rejection', shortlist: 'Shortlist', reject: 'Reject', accept: 'Accept',
  },
  wallet: {
    title: 'Wallet & Points', sub: 'Services are paid in points — topped up electronically and used inside the platform only.',
    balance: 'Your balance', pts: 'points', choose: 'Choose a top-up package', bonus: 'bonus', buy: 'Top up',
    payWith: 'Electronic payment methods', payNote: 'Gateways are linked from the admin panel (mada, Apple Pay, Visa/Mastercard, STC Pay).',
    nonRefund: 'Points are non-refundable: credited to your account only, not redeemable for cash, not transferable. Details in the',
    policy: 'Payment & Refund Policy', history: 'Transactions', chargeOk: 'Top-up successful (demo mode)',
    sar: 'SAR',
  },
  admin: {
    title: 'Admin Panel', sub: 'Full control: data, accounts, content, ads, pricing, payments, and integrations',
    tDash: 'KPIs', tUsers: 'Accounts', tJobs: 'Jobs', tContent: 'Content', tAds: 'Ads', tPricing: 'Pricing & Plans', tPoints: 'Points', tPayments: 'E-Payment', tAi: 'AI', tSocial: 'Social Login', tGeo: 'Geo Coverage', tPolicies: 'Policies',
    kpiJobs: 'Active jobs', kpiSeekers: 'Registered seekers', kpiHires: 'Successful hires', kpiSaved: 'Minutes saved/day', kpiApps: 'Applications this month', kpiEmployers: 'Registered employers',
    seedMode: 'Manual KPI seeding mode', seedOn: 'Manual — you enter the numbers (pre-launch phase)', seedOff: 'Automatic — from database analytics',
    seedNote: 'The platform starts with no data: enable manual mode, enter realistic indicators, switch off once real data accumulates.',
    save: 'Save', saved: 'Saved', edit: 'Edit', delete: 'Delete', activate: 'Activate', deactivate: 'Disable',
    heroTitle: 'Homepage headline', heroSub: 'Intro text', news: 'News & announcements', addNews: 'Add news', newsText: 'News text',
    adTop: 'Top ad banner', adBottom: '"Advertise with us" bottom space', adPrice: 'Monthly price', adEnabled: 'Enabled', adLink: 'Ad link', adText: 'Ad text',
    pkgName: 'Plan name', pkgPrice: 'Price', pkgPts: 'Points', pkgBonus: 'Bonus', cvPrice: 'CV logo-removal price', promote3: '3-day promotion price', promote7: '1-week promotion price',
    gateway: 'Payment gateway', gatewayUrl: 'Gateway URL / API key', enabled: 'Enabled', mada: 'mada', applepay: 'Apple Pay', visa: 'Visa / Mastercard', stcpay: 'STC Pay', testMode: 'Test mode',
    aiProvider: 'Provider', aiKey: 'API key', aiModel: 'Model', aiCost: 'Cost control', aiCostNote: 'Limit expensive models in repetitive ops; reserve them for high-precision tasks (CV tailoring, JD matching).', connected: 'Connected', notConnected: 'Not connected — demo mode',
    socialClient: 'Client ID', socialSecret: 'Client Secret', socialNote: 'Enter each provider\'s keys to activate social login instantly.',
    geoList: 'Covered West Riyadh neighborhoods', geoAdd: 'Add neighborhood', geoSpeed: 'Adopted average commute speed (km/h)', geoSpeedNote: 'Time = distance ÷ average speed — fix with a trusted source (pending meeting decision: 35.7 or 40).',
    policyEdit: 'Edit policy text', usersCol: 'User', roleCol: 'Role', seeker: 'Seeker', employer: 'Employer', adminRole: 'Admin',
    jobsModeration: 'Incomplete job ads cannot be published — the platform flags gaps to the employer', exportData: 'Export data',
    hoodName: 'Neighborhood name', hoodNameEn: 'English name', zone: 'Zone', coords: 'Coordinates', useMyLoc: 'Capture my current coordinates', reasons: 'Rejection reasons', addReason: 'Add reason', liveStats: 'Live from the database',
  },
  policies: {
    title: 'Policies & Terms', sub: 'Acceptance is required at signup — and holds even if links are never opened; we encourage reading them.',
    termsT: 'Terms of Use', privacyT: 'Privacy Policy', paymentT: 'Payment & Refund Policy', pointsT: 'Points Policy', aiT: 'AI & Data Controls',
  },
  common: { cancel: 'Cancel', confirm: 'Confirm', close: 'Close', back: 'Back', next: 'Next', all: 'All', demo: 'Demo mode — data stays in your browser only', yes: 'Yes', no: 'No', optional: 'Optional', required: 'Required' },
};
