import "dotenv/config";
import { getDb } from "../api/queries/connection";
import { neighborhoods, companies, jobs, settings, news, rejectionReasons, policies } from "./schema";

// ── أحياء غرب وجنوب الرياض (إحداثيات تقريبية معتمدة) ───────────────────────
const HOODS = [
  // غرب الرياض
  { nameAr: "عرقة", nameEn: "Irqah", zone: "west", lat: 24.6942, lng: 46.6039 },
  { nameAr: "حطين", nameEn: "Hittin", zone: "west", lat: 24.7593, lng: 46.6297 },
  { nameAr: "العريجاء", nameEn: "Al-Urayja", zone: "west", lat: 24.6260, lng: 46.5780 },
  { nameAr: "العريجاء الوسطى", nameEn: "Al-Urayja Al-Wusta", zone: "west", lat: 24.6330, lng: 46.5950 },
  { nameAr: "ظهرة البديعة", nameEn: "Dhahrat Al-Badi'ah", zone: "west", lat: 24.6398, lng: 46.5590 },
  { nameAr: "البديعة", nameEn: "Al-Badi'ah", zone: "west", lat: 24.6150, lng: 46.5950 },
  { nameAr: "شبرا", nameEn: "Shubra", zone: "west", lat: 24.6117, lng: 46.5680 },
  { nameAr: "السويدي", nameEn: "Al-Suwaidi", zone: "west", lat: 24.5903, lng: 46.5745 },
  { nameAr: "السويدي الغربي", nameEn: "Al-Suwaidi Al-Gharbi", zone: "west", lat: 24.5880, lng: 46.5520 },
  { nameAr: "سلطانة", nameEn: "Sultanah", zone: "west", lat: 24.6005, lng: 46.6030 },
  { nameAr: "العوالي", nameEn: "Al-Awali", zone: "west", lat: 24.6500, lng: 46.5450 },
  { nameAr: "طويق", nameEn: "Tuwaiq", zone: "west", lat: 24.5850, lng: 46.5050 },
  { nameAr: "المهدية", nameEn: "Al-Mahdiyah", zone: "west", lat: 24.6000, lng: 46.5200 },
  { nameAr: "ظهرة نمار", nameEn: "Dhahrat Namar", zone: "west", lat: 24.5680, lng: 46.5450 },
  // جنوب غرب / جنوب الرياض
  { nameAr: "نمار", nameEn: "Namar", zone: "south", lat: 24.5550, lng: 46.5400 },
  { nameAr: "ديراب", nameEn: "Dirab", zone: "south", lat: 24.5100, lng: 46.4700 },
  { nameAr: "الغروي", nameEn: "Al-Ghurwi", zone: "south", lat: 24.5530, lng: 46.5050 },
  { nameAr: "الحزم", nameEn: "Al-Hazm", zone: "south", lat: 24.5680, lng: 46.5730 },
  { nameAr: "المشعل", nameEn: "Al-Mishal", zone: "south", lat: 24.5560, lng: 46.5950 },
  { nameAr: "الشفا", nameEn: "Al-Shifa", zone: "south", lat: 24.5410, lng: 46.5760 },
  { nameAr: "بدر", nameEn: "Badr", zone: "south", lat: 24.5320, lng: 46.6040 },
  { nameAr: "المروة", nameEn: "Al-Marwah", zone: "south", lat: 24.5440, lng: 46.6200 },
  { nameAr: "الدار البيضاء", nameEn: "Al-Dar Al-Bayda", zone: "south", lat: 24.5240, lng: 46.6350 },
  { nameAr: "طيبة", nameEn: "Taybah", zone: "south", lat: 24.5380, lng: 46.6550 },
  { nameAr: "المنصورة", nameEn: "Al-Mansourah", zone: "south", lat: 24.5280, lng: 46.6680 },
  { nameAr: "العزيزية", nameEn: "Al-Aziziyah", zone: "south", lat: 24.5750, lng: 46.7550 },
] as const;

const COMPANIES = [
  { nameAr: "الأفق للتجزئة", nameEn: "Al-Ofoq Retail", sectorAr: "تجزئة", sectorEn: "Retail", color: "#0F766E", initials: "أف", verified: true },
  { nameAr: "عيادات دنتلة الطبية", nameEn: "Dentala Clinics", sectorAr: "صحة", sectorEn: "Health", color: "#7C3AED", initials: "دن", verified: true },
  { nameAr: "مدارس الرواد الأهلية", nameEn: "Al-Rowad Schools", sectorAr: "تعليم", sectorEn: "Education", color: "#EA580C", initials: "رو", verified: true },
  { nameAr: "درة التقنية", nameEn: "Durrah Tech", sectorAr: "تقنية", sectorEn: "Tech", color: "#1D4ED8", initials: "در", verified: true },
  { nameAr: "مطاعم ضيافة", nameEn: "Diyafa Restaurants", sectorAr: "ضيافة", sectorEn: "F&B", color: "#B45309", initials: "ضي", verified: false },
  { nameAr: "المسار للوجستيات", nameEn: "Al-Masar Logistics", sectorAr: "لوجستيات", sectorEn: "Logistics", color: "#374151", initials: "مس", verified: false },
  { nameAr: "فنادق الواحة الغربية", nameEn: "West Oasis Hotels", sectorAr: "سياحة", sectorEn: "Hospitality", color: "#DB2777", initials: "وا", verified: true },
];

// [companyIdx, hoodAr, titleAr, titleEn, min, max, type, skills, hoursAr, hoursEn, descAr, descEn, reqAr, reqEn, promoted?]
const JOBS: any[] = [
  [3, "عرقة", "مطوّر واجهات أمامية", "Front-End Developer", 12000, 16000, "full", ["React", "TypeScript", "Tailwind", "Vue.js"], "الأحد–الخميس، 9ص–5م", "Sun–Thu, 9am–5pm",
    "قيادة تطوير واجهات منتجاتنا الرقمية والعمل مع فريق التصميم على تجربة استخدام عربية أولاً.",
    "Own front-end development of our digital products, partnering with design on an Arabic-first UX.",
    ["خبرة 3 سنوات فأكثر بـ React أو Vue", "إتقان TypeScript وأنظمة التصميم", "اهتمام بتفاصيل تجربة المستخدم"],
    ["3+ years with React or Vue", "Strong TypeScript & design systems", "Keen eye for UX details"], true],
  [0, "ظهرة البديعة", "محاسب", "Accountant", 7000, 9500, "full", ["Excel", "ERP", "الزكاة والضريبة", "QuickBooks"], "الأحد–الخميس، 8ص–4م", "Sun–Thu, 8am–4pm",
    "إدارة القيود اليومية والتسويات البنكية وإعداد التقارير المالية الشهرية لفرع غرب الرياض.",
    "Manage daily entries, bank reconciliations and monthly financial reports for the West Riyadh branch.",
    ["بكالوريوس محاسبة", "خبرة سنتين على الأقل", "إلمام بأنظمة ERP"], ["BSc Accounting", "2+ years experience", "ERP familiarity"]],
  [1, "العريجاء", "ممرض/ممرضة", "Registered Nurse", 8000, 11000, "shift", ["رعاية مرضى", "تعقيم", "سجلات طبية", "BLS"], "ورديات صباحية ومسائية", "Morning & evening shifts",
    "تقديم الرعاية التمريضية في عيادات الأسنان ومساندة الأطباء أثناء الإجراءات.",
    "Provide nursing care in dental clinics and assist doctors during procedures.",
    ["ترخيص الهيئة السعودية للتخصصات الصحية", "خبرة سنة فأكثر", "شهادة BLS سارية"], ["SCFHS license", "1+ year experience", "Valid BLS certificate"]],
  [2, "البديعة", "معلم لغة إنجليزية", "English Teacher", 9000, 12000, "full", ["تدريس", "IELTS", "إدارة صف", "مناهج دولية"], "الأحد–الخميس، 7ص–2م", "Sun–Thu, 7am–2pm",
    "تدريس اللغة الإنجليزية للمرحلة المتوسطة وفق المنهج الدولي المعتمد لدى المدارس.",
    "Teach English to middle-school grades following the school's accredited international curriculum.",
    ["بكالوريوس لغة إنجليزية أو تعليم", "خبرة تدريس سنتين", "رخصة معلم سارية"], ["BA English or Education", "2 years teaching", "Valid teaching license"]],
  [4, "شبرا", "باريستا", "Barista", 4000, 5500, "shift", ["قهوة مختصة", "خدمة عملاء", "لاتيه آرت"], "ورديتان: 7ص–3م / 3م–11م", "Two shifts: 7am–3pm / 3pm–11pm",
    "تحضير مشروبات القهوة المختصة واستقبال العملاء في فرع شبرا.",
    "Prepare specialty coffee and welcome guests at our Shubra branch.",
    ["شغف بالقهوة المختصة", "التزام بمواعيد الورديات"], ["Passion for specialty coffee", "Shift punctuality"]],
  [5, "طويق", "مشرف مستودع", "Warehouse Supervisor", 8500, 11000, "full", ["إدارة مخزون", "WMS", "قيادة فرق", "سلامة"], "السبت–الخميس، 8ص–5م", "Sat–Thu, 8am–5pm",
    "الإشراف على عمليات الاستلام والتخزين والصرف في مستودع طويق وقيادة فريق من 12 موظفاً.",
    "Supervise receiving, storage and dispatch at the Tuwaiq warehouse, leading a team of 12.",
    ["خبرة 4 سنوات في المستودعات", "إتقان أنظمة WMS", "رخصة قيادة سارية"], ["4 years warehouse experience", "WMS proficiency", "Valid driving license"]],
  [6, "حطين", "موظف استقبال", "Front Desk Agent", 5500, 7000, "shift", ["حجوزات", "إنجليزية", "خدمة ضيوف", "Opera PMS"], "ورديات على مدار الساعة", "24/7 rotating shifts",
    "استقبال ضيوف الفندق وإدارة الحجوزات وضمان تجربة وصول استثنائية.",
    "Welcome hotel guests, manage reservations and ensure an exceptional arrival experience.",
    ["إتقان الإنجليزية تحدثاً وكتابة", "مظهر لائق وحضور مميز", "خبرة سنة في الضيافة ميزة إضافية"], ["Fluent English", "Professional presence", "1 year hospitality a plus"], true],
  [0, "السويدي", "كاشير", "Cashier", 3500, 4500, "part", ["نقاط بيع", "خدمة عملاء", "دقة"], "دوام جزئي مسائي", "Part-time evenings",
    "تشغيل نقاط البيع وخدمة العملاء في فرع السويدي بدوام جزئي مسائي.",
    "Operate POS and serve customers at the Suwaidi branch, evening part-time.",
    ["ثانوية عامة فأعلى", "دقة في التعامل مع النقد"], ["High school diploma", "Cash-handling accuracy"]],
